### ISSUE TITLE
KeyError: 'authors' while trying to get article embeddings

### ISSUE THREAD

**Issue by urmeya** [allenai/specter#6]
I am trying get SPECTER embeddings of some articles. I am using following structure for the input `metadata.json`

```
{
    'doc_id1': {'title': 'representation learning of scientific documents',
                'abstract': 'we propose a new model for representing abstracts'},
    'doc_id2': {'title': ' learning of scientific documents',
                'abstract': 'we propose a new model'}
}
```
I used embed.py command as given in README to get the embeddings but ran into following error.
Please help me solving this issue.
I was able to successfully get embeddings for `sample-metadata.json`. In this file additional metadata keys like 'authors, 'year', 'cited_by' are given. But as per documentation in  README, only `'title'` and `'abstract'` are the required fields for each article right? 

```
  0%|                                                                                                                                                                                      | 0/625 [00:00<?, ?batches/s]
Traceback (most recent call last):
  File "specter/predict_command.py", line 225, in <module>
    run()
  File "specter/predict_command.py", line 221, in run
    main(prog="allennlp")
  File "specter/predict_command.py", line 215, in main
    args.func(args)
  File "specter/predict_command.py", line 172, in _predict
    manager.run()
  File "specter/predict_command.py", line 98, in run
    for model_input_json, result in zip(batch_json, self._predict_json(batch_json)):
  File "/opt/conda/envs/specter/lib/python3.7/site-packages/allennlp/commands/predict.py", line 153, in _predict_json
    results = self._predictor.predict_batch_json(batch_data)
  File "./specter/predictor.py", line 76, in predict_batch_json
    instances.append(self._dataset_reader.text_to_instance(json_dict))
  File "./specter/data.py", line 441, in text_to_instance
    source_author, source_author_position = self._get_author_field(source_paper['authors'])
KeyError: 'authors'
```

**Comment by sergeyf** [comment]
@urmeya we just pushed a fix to this. Please pull the latest and test it out.
